name: limestone
dependencies:
  - base
  - free
  - polysemy
  - mtl
  - containers
  - exceptions
  - pretty
  - parsec
  - transformers
  - text

default-extensions:
  - AllowAmbiguousTypes
  - ApplicativeDo
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - DuplicateRecordFields
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - TypeSynonymInstances
  - UndecidableInstances
  - ViewPatterns
  - QuantifiedConstraints
  - QuasiQuotes

ghc-options: -Wall -freverse-errors -Wno-missing-pattern-synonym-signatures -Wno-orphans
library:
  source-dirs:
    - src

executables:
  limestone:
    main: Main.hs

    source-dirs:
      - app

    dependencies:
      - limestone
